### ISSUE TITLE
Please match Desktop Client in terms of: "Settings: Add enabled/disabled sign criptext footer"

### ISSUE THREAD

**Issue by szaimen** [Criptext/Android-Email-Client#536]
Reference: Criptext/Criptext-Email-React-Client#1108

**Comment by szaimen** [comment]
Reference: https://github.com/Criptext/Criptext-Email-React-Client/issues/1108

**Comment by jorgeblacio** [comment]
Hi @szaimen yes, this is something that will come out on release 0.21.4 on Monday.

**Comment by jorgeblacio** [comment]
Hi @szaimen this is out now on version 0.21.4 as promised, I'll proceed and close this issue, thanks for your feedback.
