### ISSUE TITLE
Cannot change 'from' address in replies or drafts

### ISSUE THREAD

**Issue by kylejwatson** [Criptext/Android-Email-Client#689]
**Describe the bug**
Cannot change your email address from the original email when creating replies or editing saved drafts.

**To Reproduce**
1. Go to inbox or drafts folder
2. Click on an email to open it
3. Click on the reply button or edit draft button
4. See the dropdown for selecting addresses is not in the normal 'from' box

**Expected behavior**
There should be a dropdown to select addresses like in normal email composing. 

**Screenshots (Optional)**
![Screenshot_20200830-165057_Criptext](https://user-images.githubusercontent.com/5176836/91663525-4c7ca600-eae1-11ea-87e3-b87119686acf.png)

**Device and System information (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS Version: Android 9 (P)
 - App Version: 0.23.4

**Additional information**
I think the issue lies with this function: 
https://github.com/Criptext/Android-Email-Client/blob/ce90f001c68796eb47008d9b1cfc8b68b2a9695f/src/main/kotlin/com/criptext/mail/scenes/composer/ComposerScene.kt#L261

**Comment by jorgeblacio** [comment]
Hi @kylejwatson, thanks for reportig this, I'll look into it this week. Although regarding changing from on a reply is by design not allowed in Criptext. The draft part will try to upload a new version by the end of the week or monday with the fix.
