### ISSUE TITLE
Reply to a sent email will set sender as recipient

### ISSUE THREAD

**Issue by tarbib** [Criptext/Android-Email-Client#699]
**Describe the bug**
When replying to own first email, the recipient is the criptext user's email address (not even the custom domain one) instead of the recipient email.
**To Reproduce**

1. criptext_user@customdomain.com send an email to recipient@gmail.com
2. criptext_user@customdomain.com replies to the thread (right after the first email) to recipient@gmail.com
3. In the recipient field the address shown is criptext_user@**criptext.com** instead of recipient@gmail.com

**Expected behavior**
The recipient field should be filed with the recipient address of the initial mail sent in the thread.

**Device and System information (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS Version: Android Oreo 8.0.0 
 - App Version: 0.24.0

**Comment by tarbib** [comment]
Note : this works fine on Ubuntu.

**Comment by jorgeblacio** [comment]
Thanks for reporting this, I'll look into this asap.
